apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: nsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: example/cmd-registry-memory
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        env:
        - name: REGISTRY_MEMORY_LISTEN_ON
          value: https://0.0.0.0:443/
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/spire/sockets/agent.sock
        volumeMounts:
          - name: spire-agent-socket
            mountPath: /run/spire/sockets
            readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
